version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    command: npm start
    ports:
     - ${TARGET_PORT}:${APP_PORT}
    volumes:
     - .:/usr/src/app
    networks:
     - network
  db:
    image: postgres
    ports:
     - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - data:/var/lib/postgresql/data
    networks:
     - network
networks:
  network:
    driver: bridge
volumes:
  data:
    driver: local
