version: "3.8"
services:
  node:
    build:
      context: .
    command: npm start
    ports:
     - ${TARGET_PORT}:${APP_PORT}
    volumes:
     - .:/usr/src/app
    networks:
     - network
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - data:/var/lib/postgresql/data
    networks:
     - network
networks:
  network:
    driver: bridge
volumes:
  data:
    driver: local
